name: test
main: com.github.jimyjammy.test.Plugin
version: 1.0
api-version: 1.15

commands:
   time:
      usage: /<command> [Hours] [Minuites]
   mn:
      usage: /<command>
      aliases: [menu]
   health:
      usage: /<command> [player] [Health]
      aliases: [hp]